### ISSUE TITLE
Compilation in CentOS 7

### ISSUE THREAD

**Issue by dyt811** [NIRALUser/neoseg#1]
Hi, I have attempted to compile this from source to test it out in CentOS7 but it seems to be running into issues complaining about find ITK missing? See log attached. Could you update that instruction and let me know if there is anything else I need to do to test NeoSeg out? Also, is this dependent on BrainSeg / NeoSegPipeline and are those completely separate project/repos? Thanks.

I tried both CMake 2.8 and 3.6 but both seems to be not working. 

[CMake3.6.txt](https://github.com/NIRALUser/neoseg/files/1947461/CMake3.6.txt)
[CMake2.8.txt](https://github.com/NIRALUser/neoseg/files/1947462/CMake2.8.txt)

Lastly, do you have any binaries for any platforms pre-compiled so we can just try it out on some neonatal data we have? Thanks.

**Comment by juanprietob** [comment]
You need to compile and install ITKv4.8 https://github.com/kitware/itk

**Comment by juanprietob** [comment]
Release version can be downloaded from 
https://github.com/NIRALUser/NeosegPipeline/releases
